# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Generating a build"
  lane :alpha do
    increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
    gradle(task: "assembleRelease")
    firebase_app_distribution(
        app: "1:67078834811:android:15d23c909316f74e99f0de",
        testers: "ansari.ahmed@live.com",
        # testers: "shamshudein.syedkareem@cognizant.com , manikandan.k34a613@cognizant.com",
        groups: "testers",
        release_notes: "React Native Android App New Release",
        firebase_cli_path: "/usr/local/bin/firebase",
        firebase_cli_token: "1//0g_bWZ7sOAzZ5CgYIARAAGBASNwF-L9Ir9LpUBah--uO48uv5yTq1Ojhr1yZVYP4FnooRaRbhvZskOsJQnx62DFdz1rE60L-q9so"
    )
  end
  
  
end
